### ISSUE TITLE
Update to 3.8.8

### ISSUE THREAD

**Issue by sgmihai** [juancarlospaco/nim-tinyfiledialogs#1]
https://sourceforge.net/projects/tinyfiledialogs/
Looks like the last update is 9 months old, would be nice to have, as this library is in the nimble package db.
Edit: looks like there is an updated/maintained version of the bindings in nimble: https://nimble.directory/pkg/tinydialogs
suggestion, maybe remove this from nimble as it is an outdated duplicate ?

**Comment by juancarlospaco** [comment]
> remove this from nimble as it is an outdated duplicate ?

That is not currently allowed, so I cant, feel free to report a bug to packages repo.

**Comment by juancarlospaco** [comment]
Done.
